### PR TITLE
Updated README.MD

### PR DESCRIPTION
**Pull request by niallmerrigan**
Added switches for command line

### CODE REVIEW

**Comment by byt3bl33d3r** [comment]
@niallmerrigan hey man! thanks for this, I'm going to leave this PR open as a reminder since this is something that I'll probably add in the Wiki once I start writing the docs.

**Comment by niallmerrigan** [comment]
No problem, I can start porting this to the wiki.

**Comment by pwns4cash** [comment]
Give me creds

**Comment by byt3bl33d3r** [comment]
@niallmerrigan will be adding this to the wiki shortly! thanks

**Pull request closed without merging**
