### PR TITLE
Update KarmaSMB.py

### PR DESCRIPTION
**Pull request by 0x27**
Fix crash as seen in: http://pastebin.com/SNWS1cxT

### CODE REVIEW

**Comment by 0x27** [comment]
Disregard, still testing this. It now causes a new crash that it didn't cause immediately before...

**Comment by 0x27** [comment]
Sorry about the sheer number of recommits there, testing this live on site trying to make it stop crashing 'cos of stuff.

**Comment by byt3bl33d3r** [comment]
@0x27 this is fixed by upgrading your impacket version :P see #116

**Comment by 0x27** [comment]
Aaaah, duly noted! Thanks :D

**Comment by 0x27** [comment]
Yep, that fixed it. No need for this bodge/workaround now :D Thanks!

**Comment by byt3bl33d3r** [comment]
@0x27 np !

**Pull request closed without merging**
